backend:
  name: github
  repo: navi-creator/Keepet_statick

media_folder: "site/static/img"
public_folder: "img"

collections:
  - name: "post"
    label: "Post"
    folder: "site/content/post"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  # Страницы сайта
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Главная страница"
        name: "home"
        fields:
          - {label: 🔴 SEO, name: seo, widget: object, hint: Блок для SEO, fields: [
              {label: Title, name: title, widget: string},
              {label: Description, name: description, widget: string},
              {label: Keywords, name: keywords, widget: list,
                 fields: [{label: Ключ, name: key, widget: string}]}
              ]}
          - {label:  1⃣  Первая секция, name: first_section, widget: object, hint: Первая секция, fields: [
              {label: Заголовок, name: heading, widget: string},
              {label: Слоган, name: text, widget: markdown},
              {label: Описание, name: description, widget: markdown},
              {label: Кнопки магазинов, name: button_app, widget: list,
                 fields: [
                   {label: Название, name: name, widget: string},
                   {label: Ссылка, name: link, widget: string}
                 ]}
            ]}
          - {label:  2⃣  Вторая секция, name: second_section, widget: object, hint: Вторая секция, fields: [
              {label: Заголовок, name: heading, widget: string},
              {label: Описание, name: description, widget: markdown},
              {label: Кнопки магазинов, name: button_app, widget: list,
                 fields: [
                   {label: Название, name: name, widget: string},
                   {label: Ссылка, name: link, widget: string}
                 ]}
            ]}
          - {label:  3⃣  Третья секция, name: third_section, widget: object, hint: Третья секция, fields: [
              {label: Заголовок, name: heading, widget: string},
              {label: Описание, name: description, widget: markdown},
              {label: Промо блоки, name: promo_block, widget: list,
                 fields: [
                   {label: Картинка, name: image, widget: image},
                   {label: Заголовок, name: heading, widget: string},
                   {label: Описание, name: description, widget: markdown}
                ]},
              {label: Кнопки магазинов, name: button_app, widget: list,
                 fields: [
                   {label: Название, name: name, widget: string},
                   {label: Ссылка, name: link, widget: string}
                 ]}
            ]}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
      - file: "site/content/products/_index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      - file: "site/content/values/_index.md"
        label: "Values Page"
        name: "values"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - label: Values
            name: values
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: imageUrl, widget: image}
